### ISSUE TITLE
Raw historical prices

### ISSUE THREAD

**Issue by thdoan** [Gunjan933/stock-market-scraper#4]
Hi, great project! Do you know of a source that allows me to retrieve unadjusted historical prices?

For example, the prices here should be double (i.e., in 40s range) since the stock had 2:1 split in February 2021.

https://finance.yahoo.com/quote/EXPI/history?period1=1601251200&period2=1601337600&interval=1d&filter=history&frequency=1d

https://query2.finance.yahoo.com/v8/finance/chart/EXPI?period1=1601251200&period2=1601337600&interval=1d&events=history

**Comment by gunjannandy** [comment]
Hi @thdoan,

Thanks for reaching out. We are querying YAHOO Finance api, and as far as I know, YAHOO Finance doesn't provide unadjusted historical stock prices. So I am afraid, we can't retrieve unadjusted historical prices. 

I hope that helped.

**Comment by gunjannandy** [comment]
Closing the issue, as no response. Feel free to re-open.
