### ISSUE TITLE
Financials needed

### ISSUE THREAD

**Issue by Gowtham-G-404** [Gunjan933/stock-market-scraper#7]
Is it possible to get the financials like "Income statement", "Balance Sheet" and "Cash Flow" for all stocks as well? If yes, please suggest how this can be done.

Thanks.

**Comment by gunjannandy** [comment]
Hey, I haven't looked into the recent Yahoo Finance API changes, if that supports these historical data, it shouldn't be difficult to integrate.
But if not, then we will have to see into other APIs to get the same data corresponding to the specific stocks.

Closing this issue, if needed, please feel free to re-open.
Thanks!
